DROP TABLE IF EXISTS saved_pin_to_board;
DROP TABLE IF EXISTS saved_pin_to_section;
DROP TABLE IF EXISTS saved_board;
DROP TABLE IF EXISTS follower;
DROP TABLE IF EXISTS section;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS bookmark;
DROP TABLE IF EXISTS pin;
DROP TABLE IF EXISTS board;
DROP TABLE IF EXISTS user_chat;
DROP TABLE IF EXISTS msg;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS mark;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS survey;
DROP TABLE IF EXISTS "user";


