services:
  main:
    container_name: mainService
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - '8080:8080'

  minio:
    container_name: minioService
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_storage: {}
