version: '3.8'

services:
  main:
    container_name: mainService
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - '8080:8080'
  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/pinset_data
    expose:
      - 5432
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20

volumes:
  postgres_data:
